name: docker build and run

on:
  push:
    branches: [ "main", "f/test-ngrok-with-apache" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      
      - name: download Ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          sudo apt install unzip zip -y 
          tar -xvzf ngrok-v3-stable-linux-amd64.tgz
          ls -la

      - name: docker build
        env:
          NGROK: ${{ secrets.NGROK }}
          NGROKYML: ${{ secrets.NGROKYML }}
        run: |
          echo ${#NGROK}
          echo "NGROK=$NGROK" > secret
          echo $NGROKYML > ngrok.yml
          docker build --build-arg $NGROK -t apacke_ngrok . 
          
      - name: docker run
        run: |
          echo "hi up to here"
          docker run --name httpd apacke_ngrok -d
          sleep 15
          echo "hi up to here2"
          docker exec -it httpd ngrok start --all --config /ngrok.yml
          echo "hi up to here3"
          sleep 3600
