name: docker build and run

on:
  push:
    branches: [ "main", "f/test-ngrok-with-apache" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      
      - name: download Ngrok
        run: |
          wget https://github.com/vincenthsu/systemd-ngrok/archive/refs/heads/master.zip
          apt install unzip zip -y 
          unzip master -d ./ngrok master.zip

      - name: docker build
        env:
          NGROK: ${{ secrets.NGROK }}
        run: |
          echo ${#NGROK}
          docker build --build-arg $NGROK -t apacke_ngrok . 
          
      - name: docker run
        run: |
          docker run apacke_ngrok
